plugins:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'gemfiles/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'pkg/**/*'
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'test/**/*'

Style/OptionalBooleanParameter:
  Exclude:
    - 'test/**/*'

Minitest/MultipleAssertions:
  Max: 10

Naming/FileName:
  Exclude:
    - 'lib/state_machines-audit_trail.rb'

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false