language: ruby
sudo: false
cache: bundler

script: "bundle exec rake"

services: mongodb
rvm:
  - 2.2.2
  - 2.3.1
  - jruby
  - rbx-2
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
